# Go to api.ai -> Login to your account -> Click the settings icon next to your agent -> Look for Client access token, paste it here
accesstoken: "YOURACCESSTOKEN"

# https://docs.api.ai/docs/languages
lang: "en"

# Reply to the player( true ) or show to the server( false )
replyToPlayer: false

# The name of your bot to display in chat:
botname: "&5ResponseBot: "

# The format the bot will look like in chat:
chatFormat: "[BOTNAME][RESPONSE]"

# This will be used when you use [DEFAULT] in a bot response, [DEFAULT] will be replaced with this:
defaultColor: "&4"

# If there is a prefix set, the bot will only respond to chat that begins with the defined prefix:
requiredPrefix: "?"

# If this is enabled it will send a message when a player joins your server
# if send_to_server is false, the message will only be sent to the player who joined, otherwise it will be sent to the entire server
# msg supports:
# [BOTNAME] = botname from above
# [PLAYER] = The player name who joined
# [PREFIX] = The prefix from above
on_join:
 enable: false
 send_to_server: false
 msg: "[BOTNAME]&4Hey [PLAYER], if you have any questions just ask with a [PREFIX] in front of your message, I'll do my best to help you out!"

