name: ResponseBot
version: 2.2.0
author: bittiez
main: US.bittiez.ResonseBot.main
commands:
    RB:
        description: /RB reload will reload the config file.
        usage: /RB reload
        permission: ResponseBot.reload
permissions:
    ResponseBot.reload:
        description: Allows the use of /RB reload
    ResponseBot.updates:
        description: Will receive update notifications when a new version of RB is released.